apiVersion: v1
kind: Secret
metadata:
  name: chatbot-integration-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
type: Opaque
stringData:
{{ toYaml (.Values.integrationSecrets | default dict) | indent 2 }}
