apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
spec:
  ports:
  - name: http-chatbot
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}
    protocol: TCP
  selector:
    app: chatbot
  sessionAffinity: None
  type: ClusterIP
