apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 11434
    protocol: TCP
  selector:
    app: ollama
  sessionAffinity: None
  type: ClusterIP
