# docker-build
name = "chatbot_image"
type = "docker_build"

dockerfile    = "Dockerfile"
build_timeout = "30m"

[public_repo]
repo      = "matt-zach-s/sovereign-agent-starter"
directory = "src/app"
branch    = "main"
